// src/database/seeders/textbookPdfsData.ts
// Complete Maharashtra State Board Textbooks (Classes 1 to 10)
// Auto-generated from Google Drive repository (108 books)

export interface TextbookPdfSeed {
  classNumber: number;
  medium: 'english' | 'marathi';
  subjectEnglish: string;
  subjectMarathi: string;
  titleEnglish: string;
  titleMarathi: string;
  descriptionEnglish: string;
  descriptionMarathi: string;
  fileName: string;
  relativePath: string;
  driveId: string;
}

export const textbookPdfs: TextbookPdfSeed[] = [
  {
    "classNumber": 1,
    "medium": "english",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "Balbharati English Standard 1",
    "titleMarathi": "बालभारती इंग्रजी इयत्ता १",
    "descriptionEnglish": "Maharashtra State Board Balbharati English Standard 1 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ बालभारती इंग्रजी इयत्ता १ पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_English_Medium/1st/english.pdf",
    "driveId": "1P5tt4jrusKWc2N8vzHathItp_o7bmGgl"
  },
  {
    "classNumber": 1,
    "medium": "english",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Shiku Marathi Anandane Standard 1",
    "titleMarathi": "शिका मराठी आनंदाने इयत्ता १",
    "descriptionEnglish": "Maharashtra State Board Shiku Marathi Anandane Standard 1 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ शिका मराठी आनंदाने इयत्ता १ पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_English_Medium/1st/marathi.pdf",
    "driveId": "1SPm7XX_HHKxplSFirEDEjC1KSKa09Knd"
  },
  {
    "classNumber": 1,
    "medium": "english",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Mathematics Standard 1",
    "titleMarathi": "गणित इयत्ता १",
    "descriptionEnglish": "Maharashtra State Board Mathematics Standard 1 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित इयत्ता १ पाठ्यपुस्तक",
    "fileName": "maths.pdf",
    "relativePath": "Books_English_Medium/1st/maths.pdf",
    "driveId": "1xXQnyd3sBZ2tsoNoinrFtSriF6b4kd1W"
  },
  {
    "classNumber": 2,
    "medium": "english",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "Balbharati English Standard 2",
    "titleMarathi": "बालभारती इंग्रजी इयत्ता २",
    "descriptionEnglish": "Maharashtra State Board Balbharati English Standard 2 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ बालभारती इंग्रजी इयत्ता २ पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_English_Medium/2nd/english.pdf",
    "driveId": "1jwou5J3PcPj67hKbNpR7zo489tCh2GvM"
  },
  {
    "classNumber": 2,
    "medium": "english",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Shiku Marathi Anandane Standard 2",
    "titleMarathi": "शिका मराठी आनंदाने इयत्ता २",
    "descriptionEnglish": "Maharashtra State Board Shiku Marathi Anandane Standard 2 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ शिका मराठी आनंदाने इयत्ता २ पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_English_Medium/2nd/marathi.pdf",
    "driveId": "1qveJH1py4wA6YzI3eP2bxuid0JOGsW9p"
  },
  {
    "classNumber": 2,
    "medium": "english",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Mathematics Standard 2",
    "titleMarathi": "गणित इयत्ता २",
    "descriptionEnglish": "Maharashtra State Board Mathematics Standard 2 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित इयत्ता २ पाठ्यपुस्तक",
    "fileName": "maths.pdf",
    "relativePath": "Books_English_Medium/2nd/maths.pdf",
    "driveId": "14yA823d8dCiIlcHMMj4VWOaQ3XvnXRJw"
  },
  {
    "classNumber": 3,
    "medium": "english",
    "subjectEnglish": "Art Education",
    "subjectMarathi": "कला शिक्षण",
    "titleEnglish": "Art Education Standard 3",
    "titleMarathi": "कला शिक्षण इयत्ता ३",
    "descriptionEnglish": "Maharashtra State Board Art Education Standard 3 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ कला शिक्षण इयत्ता ३ पाठ्यपुस्तक",
    "fileName": "art education.pdf",
    "relativePath": "Books_English_Medium/3rd/art education.pdf",
    "driveId": "1b3SdLwQF_ctedz_C0MYVPFbpkUo1-7Ql"
  },
  {
    "classNumber": 3,
    "medium": "english",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "Balbharati English Standard 3",
    "titleMarathi": "बालभारती इंग्रजी इयत्ता ३",
    "descriptionEnglish": "Maharashtra State Board Balbharati English Standard 3 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ बालभारती इंग्रजी इयत्ता ३ पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_English_Medium/3rd/english.pdf",
    "driveId": "1J4lTfkX_2LBqiIPll1Kutow5OBJDJUA2"
  },
  {
    "classNumber": 3,
    "medium": "english",
    "subjectEnglish": "Environmental Studies",
    "subjectMarathi": "परिसर अभ्यास",
    "titleEnglish": "Environmental Studies Part 2 Standard 3",
    "titleMarathi": "परिसर अभ्यास भाग २ इयत्ता ३",
    "descriptionEnglish": "Maharashtra State Board Environmental Studies Part 2 Standard 3 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ परिसर अभ्यास भाग २ इयत्ता ३ पाठ्यपुस्तक",
    "fileName": "world around us part 2.pdf",
    "relativePath": "Books_English_Medium/3rd/world around us part 2.pdf",
    "driveId": "1SptMcc6GJUnCL-NHG3vRX8ZnlZ78IpZ3"
  },
  {
    "classNumber": 3,
    "medium": "english",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Marathi Standard 3",
    "titleMarathi": "मराठी इयत्ता ३",
    "descriptionEnglish": "Maharashtra State Board Marathi Standard 3 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ मराठी इयत्ता ३ पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_English_Medium/3rd/marathi.pdf",
    "driveId": "1Lp6Pp2Q3Od-KhrWEq--DNgTjiyl-htJj"
  },
  {
    "classNumber": 3,
    "medium": "english",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Mathematics Standard 3",
    "titleMarathi": "गणित इयत्ता ३",
    "descriptionEnglish": "Maharashtra State Board Mathematics Standard 3 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित इयत्ता ३ पाठ्यपुस्तक",
    "fileName": "maths.pdf",
    "relativePath": "Books_English_Medium/3rd/maths.pdf",
    "driveId": "1jHT5WD0UcZ4axG0wXIVhuUmrlBebfm-y"
  },
  {
    "classNumber": 3,
    "medium": "english",
    "subjectEnglish": "Physical Education",
    "subjectMarathi": "शारीरिक शिक्षण व आरोग्य",
    "titleEnglish": "Physical Education and Health Standard 3",
    "titleMarathi": "शारीरिक शिक्षण व आरोग्य इयत्ता ३",
    "descriptionEnglish": "Maharashtra State Board Physical Education and Health Standard 3 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ शारीरिक शिक्षण व आरोग्य इयत्ता ३ पाठ्यपुस्तक",
    "fileName": "physical education.pdf",
    "relativePath": "Books_English_Medium/3rd/physical education.pdf",
    "driveId": "1N0S6O5LDCCqD_E5Ea29QPRLESVMYXoxn"
  },
  {
    "classNumber": 3,
    "medium": "english",
    "subjectEnglish": "Work Education",
    "subjectMarathi": "कार्यानुभव",
    "titleEnglish": "Work Education Standard 3",
    "titleMarathi": "कार्यानुभव इयत्ता ३",
    "descriptionEnglish": "Maharashtra State Board Work Education Standard 3 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ कार्यानुभव इयत्ता ३ पाठ्यपुस्तक",
    "fileName": "work education.pdf",
    "relativePath": "Books_English_Medium/3rd/work education.pdf",
    "driveId": "1bfcocsKntDUCYnHdm5LHAXtzSTmIyu1u"
  },
  {
    "classNumber": 4,
    "medium": "english",
    "subjectEnglish": "Art Education",
    "subjectMarathi": "कला शिक्षण",
    "titleEnglish": "Music and Art Education Standard 4",
    "titleMarathi": "संगीत व कला शिक्षण इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Music and Art Education Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ संगीत व कला शिक्षण इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "musical.pdf",
    "relativePath": "Books_English_Medium/4th/musical.pdf",
    "driveId": "1bDIwAqOt9UkIIuWr344yUMlHh8MCAH90"
  },
  {
    "classNumber": 4,
    "medium": "english",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "Balbharati English Standard 4",
    "titleMarathi": "बालभारती इंग्रजी इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Balbharati English Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ बालभारती इंग्रजी इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_English_Medium/4th/english.pdf",
    "driveId": "1Yt0DPfbKtW676aR7FRpa54G1_HsZYahJ"
  },
  {
    "classNumber": 4,
    "medium": "english",
    "subjectEnglish": "Environmental Studies",
    "subjectMarathi": "परिसर अभ्यास",
    "titleEnglish": "Environmental Studies Part 1 Standard 4",
    "titleMarathi": "परिसर अभ्यास भाग १ इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Environmental Studies Part 1 Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ परिसर अभ्यास भाग १ इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "world around us.pdf",
    "relativePath": "Books_English_Medium/4th/world around us.pdf",
    "driveId": "11kBE1WXncOKzWGCBM64qZHs7XLLb1DNH"
  },
  {
    "classNumber": 4,
    "medium": "english",
    "subjectEnglish": "History",
    "subjectMarathi": "इतिहास",
    "titleEnglish": "Shivchhatrapati Environmental Studies Part 2 (History) Standard 4",
    "titleMarathi": "शिवछत्रपती परिसर अभ्यास भाग २ (इतिहास) इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Shivchhatrapati Environmental Studies Part 2 (History) Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ शिवछत्रपती परिसर अभ्यास भाग २ (इतिहास) इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "history.pdf",
    "relativePath": "Books_English_Medium/4th/history.pdf",
    "driveId": "1m0R81R8d_EYwf4_YhCO1-7mFzYG6fOeB"
  },
  {
    "classNumber": 4,
    "medium": "english",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Marathi Standard 4",
    "titleMarathi": "मराठी इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Marathi Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ मराठी इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_English_Medium/4th/marathi.pdf",
    "driveId": "1B2jV_c84kUZUQKZ7-VSshyeq4VHQA7B9"
  },
  {
    "classNumber": 4,
    "medium": "english",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Mathematics Standard 4",
    "titleMarathi": "गणित इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Mathematics Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "maths.pdf",
    "relativePath": "Books_English_Medium/4th/maths.pdf",
    "driveId": "1OVSMYEmXjLQtoOCDlFbsFlJOjh0qaSE3"
  },
  {
    "classNumber": 4,
    "medium": "english",
    "subjectEnglish": "Physical Education",
    "subjectMarathi": "शारीरिक शिक्षण व आरोग्य",
    "titleEnglish": "Physical Education and Health Standard 4",
    "titleMarathi": "शारीरिक शिक्षण व आरोग्य इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Physical Education and Health Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ शारीरिक शिक्षण व आरोग्य इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "physical education.pdf",
    "relativePath": "Books_English_Medium/4th/physical education.pdf",
    "driveId": "1Ftuhh9o4TE6Ujjj0CDwJDIGljEwYLe--"
  },
  {
    "classNumber": 4,
    "medium": "english",
    "subjectEnglish": "Work Education",
    "subjectMarathi": "कार्यानुभव",
    "titleEnglish": "Work Education Standard 4",
    "titleMarathi": "कार्यानुभव इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Work Education Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ कार्यानुभव इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "work education.pdf",
    "relativePath": "Books_English_Medium/4th/work education.pdf",
    "driveId": "1w1cOVl5HqCn8iTahFcH64KzOZ5XfT8kL"
  },
  {
    "classNumber": 5,
    "medium": "english",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "Balbharati English Standard 5",
    "titleMarathi": "बालभारती इंग्रजी इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Balbharati English Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ बालभारती इंग्रजी इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_English_Medium/5th/english.pdf",
    "driveId": "1AohX2pi1-hkIJRrzvUL3jIkL44EJhEC8"
  },
  {
    "classNumber": 5,
    "medium": "english",
    "subjectEnglish": "Environmental Studies",
    "subjectMarathi": "परिसर अभ्यास",
    "titleEnglish": "Environmental Studies Part 1 Standard 5",
    "titleMarathi": "परिसर अभ्यास भाग १ इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Environmental Studies Part 1 Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ परिसर अभ्यास भाग १ इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "environment.pdf",
    "relativePath": "Books_English_Medium/5th/environment.pdf",
    "driveId": "1z4E4lRQfZ2_if80XtdHBf6w-jnfP1FZo"
  },
  {
    "classNumber": 5,
    "medium": "english",
    "subjectEnglish": "Hindi",
    "subjectMarathi": "हिंदी",
    "titleEnglish": "Sugambharti Hindi Standard 5",
    "titleMarathi": "सुगमभारती हिंदी इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Sugambharti Hindi Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ सुगमभारती हिंदी इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "hindi sugam.pdf",
    "relativePath": "Books_English_Medium/5th/hindi sugam.pdf",
    "driveId": "1-NsDZGdAdEAenyL0TgOxiE1ds4J148aT"
  },
  {
    "classNumber": 5,
    "medium": "english",
    "subjectEnglish": "Hindi",
    "subjectMarathi": "हिंदी",
    "titleEnglish": "Sulabhbharati Hindi Standard 5",
    "titleMarathi": "सुलभभारती हिंदी इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Sulabhbharati Hindi Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ सुलभभारती हिंदी इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "hindi sulabh.pdf",
    "relativePath": "Books_English_Medium/5th/hindi sulabh.pdf",
    "driveId": "1TaDKbXtfVWvyW4gzROTrosJ0u-tZ0Sr1"
  },
  {
    "classNumber": 5,
    "medium": "english",
    "subjectEnglish": "History",
    "subjectMarathi": "इतिहास",
    "titleEnglish": "Environmental Studies Part 2 (History) Standard 5",
    "titleMarathi": "परिसर अभ्यास भाग २ (इतिहास) इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Environmental Studies Part 2 (History) Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ परिसर अभ्यास भाग २ (इतिहास) इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "history.pdf",
    "relativePath": "Books_English_Medium/5th/history.pdf",
    "driveId": "1EjdMnmfSZBCNc_PFUWeP2SKlujqieMHB"
  },
  {
    "classNumber": 5,
    "medium": "english",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Sugambharti Marathi Standard 5",
    "titleMarathi": "सुगमभारती मराठी इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Sugambharti Marathi Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ सुगमभारती मराठी इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "marathi sugam.pdf",
    "relativePath": "Books_English_Medium/5th/marathi sugam.pdf",
    "driveId": "1Ckn_f3F7xfrUca9isrSmVfY_LEygeANb"
  },
  {
    "classNumber": 5,
    "medium": "english",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Sulabhbharati Marathi Standard 5",
    "titleMarathi": "सुलभभारती मराठी इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Sulabhbharati Marathi Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ सुलभभारती मराठी इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_English_Medium/5th/marathi.pdf",
    "driveId": "1N0RLzU3Xq92NRb2iNIPU2A7P_b9q3QQu"
  },
  {
    "classNumber": 5,
    "medium": "english",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Mathematics Standard 5",
    "titleMarathi": "गणित इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Mathematics Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "maths.pdf",
    "relativePath": "Books_English_Medium/5th/maths.pdf",
    "driveId": "1moacY_yejp1wvcqznjbtD3FgvFjZwkIc"
  },
  {
    "classNumber": 5,
    "medium": "english",
    "subjectEnglish": "Work Education",
    "subjectMarathi": "कार्यानुभव",
    "titleEnglish": "Play, Do, Learn Standard 5",
    "titleMarathi": "खेळू, करू, शिकू इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Play, Do, Learn Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ खेळू, करू, शिकू इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "play do learn.pdf",
    "relativePath": "Books_English_Medium/5th/play do learn.pdf",
    "driveId": "1aVqAomxz93B_UO3RdtBiJNMoqML8LaVO"
  },
  {
    "classNumber": 1,
    "medium": "marathi",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "My English Book Standard 1",
    "titleMarathi": "माय इंग्लिश बुक इयत्ता १",
    "descriptionEnglish": "Maharashtra State Board My English Book Standard 1 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ माय इंग्लिश बुक इयत्ता १ पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_Marathi_Medium/1st/english.pdf",
    "driveId": "19oDcPN_jJtOtCHKYK2poIvvBb11B8NcT"
  },
  {
    "classNumber": 1,
    "medium": "marathi",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Balbharati Marathi Standard 1",
    "titleMarathi": "बालभारती मराठी इयत्ता १",
    "descriptionEnglish": "Maharashtra State Board Balbharati Marathi Standard 1 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ बालभारती मराठी इयत्ता १ पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_Marathi_Medium/1st/marathi.pdf",
    "driveId": "1B10HTn6AscLAdZAKsbm2X8XSgkhdRVtU"
  },
  {
    "classNumber": 1,
    "medium": "marathi",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Ganit Standard 1",
    "titleMarathi": "गणित इयत्ता १",
    "descriptionEnglish": "Maharashtra State Board Ganit Standard 1 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित इयत्ता १ पाठ्यपुस्तक",
    "fileName": "maths.pdf",
    "relativePath": "Books_Marathi_Medium/1st/maths.pdf",
    "driveId": "1J1RDqdLygEuRMSwvOfXoAer6YHsE285G"
  },
  {
    "classNumber": 2,
    "medium": "marathi",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "My English Book Standard 2",
    "titleMarathi": "माय इंग्लिश बुक इयत्ता २",
    "descriptionEnglish": "Maharashtra State Board My English Book Standard 2 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ माय इंग्लिश बुक इयत्ता २ पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_Marathi_Medium/2nd/english.pdf",
    "driveId": "1bpmePMjMO4trNf_VSheeoD-aSuxyFUQ5"
  },
  {
    "classNumber": 2,
    "medium": "marathi",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Balbharati Marathi Standard 2",
    "titleMarathi": "बालभारती मराठी इयत्ता २",
    "descriptionEnglish": "Maharashtra State Board Balbharati Marathi Standard 2 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ बालभारती मराठी इयत्ता २ पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_Marathi_Medium/2nd/marathi.pdf",
    "driveId": "1_mP1I4Pi8b4mfP9UB53VA6UOXdQKdctx"
  },
  {
    "classNumber": 2,
    "medium": "marathi",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Ganit Standard 2",
    "titleMarathi": "गणित इयत्ता २",
    "descriptionEnglish": "Maharashtra State Board Ganit Standard 2 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित इयत्ता २ पाठ्यपुस्तक",
    "fileName": "maths.pdf",
    "relativePath": "Books_Marathi_Medium/2nd/maths.pdf",
    "driveId": "1rr-l0r2Uf0EJbKbmHPUZKFXTg4zgoMXi"
  },
  {
    "classNumber": 3,
    "medium": "marathi",
    "subjectEnglish": "Art Education",
    "subjectMarathi": "कला शिक्षण",
    "titleEnglish": "Art Education Standard 3",
    "titleMarathi": "कला शिक्षण इयत्ता ३",
    "descriptionEnglish": "Maharashtra State Board Art Education Standard 3 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ कला शिक्षण इयत्ता ३ पाठ्यपुस्तक",
    "fileName": "kala shikshan.pdf",
    "relativePath": "Books_Marathi_Medium/3rd/kala shikshan.pdf",
    "driveId": "1GJT_ymGSlLXIcKylxnQf4egBQFTUcA7a"
  },
  {
    "classNumber": 3,
    "medium": "marathi",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "My English Book Standard 3",
    "titleMarathi": "माय इंग्लिश बुक इयत्ता ३",
    "descriptionEnglish": "Maharashtra State Board My English Book Standard 3 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ माय इंग्लिश बुक इयत्ता ३ पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_Marathi_Medium/3rd/english.pdf",
    "driveId": "16UECEKlqr481DQya2EdQ62Ky09PwtqVa"
  },
  {
    "classNumber": 3,
    "medium": "marathi",
    "subjectEnglish": "History",
    "subjectMarathi": "इतिहास व नागरिकशास्त्र",
    "titleEnglish": "History and Civics Standard 3",
    "titleMarathi": "इतिहास व नागरिकशास्त्र इयत्ता ३",
    "descriptionEnglish": "Maharashtra State Board History and Civics Standard 3 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ इतिहास व नागरिकशास्त्र इयत्ता ३ पाठ्यपुस्तक",
    "fileName": "history.pdf",
    "relativePath": "Books_Marathi_Medium/3rd/history.pdf",
    "driveId": "1z7TZDZiti-GJxQNVcy6vFg0JyUO6cW6a"
  },
  {
    "classNumber": 3,
    "medium": "marathi",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Balbharati Marathi Standard 3",
    "titleMarathi": "बालभारती मराठी इयत्ता ३",
    "descriptionEnglish": "Maharashtra State Board Balbharati Marathi Standard 3 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ बालभारती मराठी इयत्ता ३ पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_Marathi_Medium/3rd/marathi.pdf",
    "driveId": "1L3yzu655uuL43p8M00EdPKOlSIWDmEHk"
  },
  {
    "classNumber": 3,
    "medium": "marathi",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Ganit Standard 3",
    "titleMarathi": "गणित इयत्ता ३",
    "descriptionEnglish": "Maharashtra State Board Ganit Standard 3 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित इयत्ता ३ पाठ्यपुस्तक",
    "fileName": "maths.pdf",
    "relativePath": "Books_Marathi_Medium/3rd/maths.pdf",
    "driveId": "1BLoxajNqiDkJUI78e_LdnSvvcjslm5Ya"
  },
  {
    "classNumber": 3,
    "medium": "marathi",
    "subjectEnglish": "Physical Education",
    "subjectMarathi": "शारीरिक शिक्षण व आरोग्य",
    "titleEnglish": "Physical Education and Health Standard 3",
    "titleMarathi": "शारीरिक शिक्षण व आरोग्य इयत्ता ३",
    "descriptionEnglish": "Maharashtra State Board Physical Education and Health Standard 3 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ शारीरिक शिक्षण व आरोग्य इयत्ता ३ पाठ्यपुस्तक",
    "fileName": "physical eduaction.pdf",
    "relativePath": "Books_Marathi_Medium/3rd/physical eduaction.pdf",
    "driveId": "1RlfNfcEYyayo0FfdfrjpaMwv-FOcLf38"
  },
  {
    "classNumber": 3,
    "medium": "marathi",
    "subjectEnglish": "Work Education",
    "subjectMarathi": "कार्यानुभव",
    "titleEnglish": "Work Education Standard 3",
    "titleMarathi": "कार्यानुभव इयत्ता ३",
    "descriptionEnglish": "Maharashtra State Board Work Education Standard 3 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ कार्यानुभव इयत्ता ३ पाठ्यपुस्तक",
    "fileName": "karayshikshan.pdf",
    "relativePath": "Books_Marathi_Medium/3rd/karayshikshan.pdf",
    "driveId": "1NX3-cN6KWnD9yb7U9cF5lc809SdQqQn4"
  },
  {
    "classNumber": 4,
    "medium": "marathi",
    "subjectEnglish": "Art Education",
    "subjectMarathi": "कला शिक्षण",
    "titleEnglish": "Art Education Standard 4",
    "titleMarathi": "कला शिक्षण इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Art Education Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ कला शिक्षण इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "kala shikshan.pdf",
    "relativePath": "Books_Marathi_Medium/4th/kala shikshan.pdf",
    "driveId": "1hruUUNQTgZSE32LhhtkJFP8gW8tdZcA4"
  },
  {
    "classNumber": 4,
    "medium": "marathi",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "My English Book Standard 4",
    "titleMarathi": "माय इंग्लिश बुक इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board My English Book Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ माय इंग्लिश बुक इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_Marathi_Medium/4th/english.pdf",
    "driveId": "1yBi5xM8l-SQw-dwTYBsVm0VWAGeDWoFz"
  },
  {
    "classNumber": 4,
    "medium": "marathi",
    "subjectEnglish": "Environmental Studies",
    "subjectMarathi": "परिसर अभ्यास",
    "titleEnglish": "Environmental Studies Part 1 Standard 4",
    "titleMarathi": "परिसर अभ्यास भाग १ इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Environmental Studies Part 1 Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ परिसर अभ्यास भाग १ इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "environment.pdf",
    "relativePath": "Books_Marathi_Medium/4th/environment.pdf",
    "driveId": "1CSRDDrf8ZPnpiTvjAy5hRJBQRSr8zvG4"
  },
  {
    "classNumber": 4,
    "medium": "marathi",
    "subjectEnglish": "History",
    "subjectMarathi": "इतिहास",
    "titleEnglish": "Shivchhatrapati Environmental Studies Part 2 (History) Standard 4",
    "titleMarathi": "शिवछत्रपती परिसर अभ्यास भाग २ (इतिहास) इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Shivchhatrapati Environmental Studies Part 2 (History) Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ शिवछत्रपती परिसर अभ्यास भाग २ (इतिहास) इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "history.pdf",
    "relativePath": "Books_Marathi_Medium/4th/history.pdf",
    "driveId": "1ulRmlI2coXqDx0WGuS_qOpl-YqqYiYNA"
  },
  {
    "classNumber": 4,
    "medium": "marathi",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Balbharati Marathi Standard 4",
    "titleMarathi": "बालभारती मराठी इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Balbharati Marathi Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ बालभारती मराठी इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_Marathi_Medium/4th/marathi.pdf",
    "driveId": "1NjEZzML4GGXDqdWHOAew4UwH8EN1ZAGb"
  },
  {
    "classNumber": 4,
    "medium": "marathi",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Ganit Standard 4",
    "titleMarathi": "गणित इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Ganit Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "maths.pdf",
    "relativePath": "Books_Marathi_Medium/4th/maths.pdf",
    "driveId": "1zYnBWJk0Bc3jhqnuT_MkwSzcthnDvwPc"
  },
  {
    "classNumber": 4,
    "medium": "marathi",
    "subjectEnglish": "Physical Education",
    "subjectMarathi": "शारीरिक शिक्षण व आरोग्य",
    "titleEnglish": "Physical Education and Health Standard 4",
    "titleMarathi": "शारीरिक शिक्षण व आरोग्य इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Physical Education and Health Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ शारीरिक शिक्षण व आरोग्य इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "physical eduations.pdf",
    "relativePath": "Books_Marathi_Medium/4th/physical eduations.pdf",
    "driveId": "1goUvcdjhms_y-OUfeubYA8kkpfQKHB9S"
  },
  {
    "classNumber": 4,
    "medium": "marathi",
    "subjectEnglish": "Work Education",
    "subjectMarathi": "कार्यानुभव",
    "titleEnglish": "Work Education Standard 4",
    "titleMarathi": "कार्यानुभव इयत्ता ४",
    "descriptionEnglish": "Maharashtra State Board Work Education Standard 4 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ कार्यानुभव इयत्ता ४ पाठ्यपुस्तक",
    "fileName": "karyashikshan.pdf",
    "relativePath": "Books_Marathi_Medium/4th/karyashikshan.pdf",
    "driveId": "1YmHAk33VUBineMbBSlnAOI1JOETu4J7d"
  },
  {
    "classNumber": 5,
    "medium": "marathi",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "My English Book Standard 5",
    "titleMarathi": "माय इंग्लिश बुक इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board My English Book Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ माय इंग्लिश बुक इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_Marathi_Medium/5th/english.pdf",
    "driveId": "14N7NW9jjEOo8IXuijKEilE72eCbUueV2"
  },
  {
    "classNumber": 5,
    "medium": "marathi",
    "subjectEnglish": "Environmental Studies",
    "subjectMarathi": "परिसर अभ्यास",
    "titleEnglish": "Environmental Studies Part 1 Standard 5",
    "titleMarathi": "परिसर अभ्यास भाग १ इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Environmental Studies Part 1 Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ परिसर अभ्यास भाग १ इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "evs.pdf",
    "relativePath": "Books_Marathi_Medium/5th/evs.pdf",
    "driveId": "19AmhJspEHQhnLpoP5bXxmswa0lA3xO07"
  },
  {
    "classNumber": 5,
    "medium": "marathi",
    "subjectEnglish": "Hindi",
    "subjectMarathi": "हिंदी",
    "titleEnglish": "Sugambharti Hindi Standard 5",
    "titleMarathi": "सुगमभारती हिंदी इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Sugambharti Hindi Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ सुगमभारती हिंदी इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "hindi 2.pdf",
    "relativePath": "Books_Marathi_Medium/5th/hindi 2.pdf",
    "driveId": "12N4DRt_6BEnK-hMDV2VsVecq9B3OSNvi"
  },
  {
    "classNumber": 5,
    "medium": "marathi",
    "subjectEnglish": "Hindi",
    "subjectMarathi": "हिंदी",
    "titleEnglish": "Sulabhbharati Hindi Standard 5",
    "titleMarathi": "सुलभभारती हिंदी इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Sulabhbharati Hindi Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ सुलभभारती हिंदी इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "hindi.pdf",
    "relativePath": "Books_Marathi_Medium/5th/hindi.pdf",
    "driveId": "1fhbGlzzCtuAO56uLQsrbIzimlr8kJWZM"
  },
  {
    "classNumber": 5,
    "medium": "marathi",
    "subjectEnglish": "History",
    "subjectMarathi": "इतिहास",
    "titleEnglish": "Environmental Studies Part 2 (History) Standard 5",
    "titleMarathi": "परिसर अभ्यास भाग २ (इतिहास) इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Environmental Studies Part 2 (History) Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ परिसर अभ्यास भाग २ (इतिहास) इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "history.pdf",
    "relativePath": "Books_Marathi_Medium/5th/history.pdf",
    "driveId": "1PEV-xB9YKaYok5CWDzt4Ihp6cnKvUsMe"
  },
  {
    "classNumber": 5,
    "medium": "marathi",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Balbharati Marathi Standard 5",
    "titleMarathi": "बालभारती मराठी इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Balbharati Marathi Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ बालभारती मराठी इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_Marathi_Medium/5th/marathi.pdf",
    "driveId": "1EzTLTMJOJWTWvggEYtpm1KElCaSUlla6"
  },
  {
    "classNumber": 5,
    "medium": "marathi",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Sugambharti Marathi Standard 5",
    "titleMarathi": "सुगमभारती मराठी इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Sugambharti Marathi Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ सुगमभारती मराठी इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "marathi 1.pdf",
    "relativePath": "Books_Marathi_Medium/5th/marathi 1.pdf",
    "driveId": "1Q7W87Hn3SmCxEu_FbultKwTztkKTBbmN"
  },
  {
    "classNumber": 5,
    "medium": "marathi",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Ganit Standard 5",
    "titleMarathi": "गणित इयत्ता ५",
    "descriptionEnglish": "Maharashtra State Board Ganit Standard 5 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित इयत्ता ५ पाठ्यपुस्तक",
    "fileName": "maths.pdf",
    "relativePath": "Books_Marathi_Medium/5th/maths.pdf",
    "driveId": "13ljL311aYYcxXUeOShLA6tAkzFtVEqGM"
  },
  {
    "classNumber": 6,
    "medium": "marathi",
    "subjectEnglish": "Art Education",
    "subjectMarathi": "कला शिक्षण",
    "titleEnglish": "Art Education Standard 6",
    "titleMarathi": "कला शिक्षण इयत्ता ६",
    "descriptionEnglish": "Maharashtra State Board Art Education Standard 6 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ कला शिक्षण इयत्ता ६ पाठ्यपुस्तक",
    "fileName": "kala shikshan.pdf",
    "relativePath": "Books_Marathi_Medium/6th/kala shikshan.pdf",
    "driveId": "1mVYNb6A-Ef76gOGUOBtSnFsVJStLd3zm"
  },
  {
    "classNumber": 6,
    "medium": "marathi",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "My English Book Standard 6",
    "titleMarathi": "माय इंग्लिश बुक इयत्ता ६",
    "descriptionEnglish": "Maharashtra State Board My English Book Standard 6 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ माय इंग्लिश बुक इयत्ता ६ पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_Marathi_Medium/6th/english.pdf",
    "driveId": "1W1bwW6_DLfEsuiQUBOADnfQo15O-aOZ7"
  },
  {
    "classNumber": 6,
    "medium": "marathi",
    "subjectEnglish": "Geography",
    "subjectMarathi": "भूगोल",
    "titleEnglish": "Geography Standard 6",
    "titleMarathi": "भूगोल इयत्ता ६",
    "descriptionEnglish": "Maharashtra State Board Geography Standard 6 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ भूगोल इयत्ता ६ पाठ्यपुस्तक",
    "fileName": "geography.pdf",
    "relativePath": "Books_Marathi_Medium/6th/geography.pdf",
    "driveId": "1rHxXCY3zJrUBAsN16vGtfhxkdth6PBVL"
  },
  {
    "classNumber": 6,
    "medium": "marathi",
    "subjectEnglish": "History",
    "subjectMarathi": "इतिहास व नागरिकशास्त्र",
    "titleEnglish": "History and Civics Standard 6",
    "titleMarathi": "इतिहास व नागरिकशास्त्र इयत्ता ६",
    "descriptionEnglish": "Maharashtra State Board History and Civics Standard 6 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ इतिहास व नागरिकशास्त्र इयत्ता ६ पाठ्यपुस्तक",
    "fileName": "history.pdf",
    "relativePath": "Books_Marathi_Medium/6th/history.pdf",
    "driveId": "1sEOFIw8zmLdWR-JGDsYsL3rTrRNb0Vja"
  },
  {
    "classNumber": 6,
    "medium": "marathi",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Balbharati Marathi Standard 6",
    "titleMarathi": "बालभारती मराठी इयत्ता ६",
    "descriptionEnglish": "Maharashtra State Board Balbharati Marathi Standard 6 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ बालभारती मराठी इयत्ता ६ पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_Marathi_Medium/6th/marathi.pdf",
    "driveId": "1ghvqaD2A3JDH3Gkm9E_tLZ9m-rMgC_AH"
  },
  {
    "classNumber": 6,
    "medium": "marathi",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Ganit Standard 6",
    "titleMarathi": "गणित इयत्ता ६",
    "descriptionEnglish": "Maharashtra State Board Ganit Standard 6 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित इयत्ता ६ पाठ्यपुस्तक",
    "fileName": "maths.pdf",
    "relativePath": "Books_Marathi_Medium/6th/maths.pdf",
    "driveId": "1p4Tsw38GUUmdGXBbymVBya3TvMhsRmBf"
  },
  {
    "classNumber": 6,
    "medium": "marathi",
    "subjectEnglish": "Physical Education",
    "subjectMarathi": "शारीरिक शिक्षण व आरोग्य",
    "titleEnglish": "Physical Education and Health Standard 6",
    "titleMarathi": "शारीरिक शिक्षण व आरोग्य इयत्ता ६",
    "descriptionEnglish": "Maharashtra State Board Physical Education and Health Standard 6 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ शारीरिक शिक्षण व आरोग्य इयत्ता ६ पाठ्यपुस्तक",
    "fileName": "physical education.pdf",
    "relativePath": "Books_Marathi_Medium/6th/physical education.pdf",
    "driveId": "1spEnVw7DKJtlQ5y2OCc7bBPtNXRubRCC"
  },
  {
    "classNumber": 6,
    "medium": "marathi",
    "subjectEnglish": "Science",
    "subjectMarathi": "सामान्य विज्ञान",
    "titleEnglish": "General Science Standard 6",
    "titleMarathi": "सामान्य विज्ञान इयत्ता ६",
    "descriptionEnglish": "Maharashtra State Board General Science Standard 6 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ सामान्य विज्ञान इयत्ता ६ पाठ्यपुस्तक",
    "fileName": "science.pdf",
    "relativePath": "Books_Marathi_Medium/6th/science.pdf",
    "driveId": "1ZgSKIHWLNamTxEdDQsZhDKOLHjdCTt6d"
  },
  {
    "classNumber": 7,
    "medium": "marathi",
    "subjectEnglish": "Art Education",
    "subjectMarathi": "कला शिक्षण",
    "titleEnglish": "Art Education Standard 7",
    "titleMarathi": "कला शिक्षण इयत्ता ७",
    "descriptionEnglish": "Maharashtra State Board Art Education Standard 7 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ कला शिक्षण इयत्ता ७ पाठ्यपुस्तक",
    "fileName": "kala.pdf",
    "relativePath": "Books_Marathi_Medium/7th/kala.pdf",
    "driveId": "18spq_g1BItBmw4wqZfVIm850gXCafhYL"
  },
  {
    "classNumber": 7,
    "medium": "marathi",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "My English Book Standard 7",
    "titleMarathi": "माय इंग्लिश बुक इयत्ता ७",
    "descriptionEnglish": "Maharashtra State Board My English Book Standard 7 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ माय इंग्लिश बुक इयत्ता ७ पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_Marathi_Medium/7th/english.pdf",
    "driveId": "1xI3BSptk7gor8pBnHw_vHB-sy-AeJycD"
  },
  {
    "classNumber": 7,
    "medium": "marathi",
    "subjectEnglish": "Geography",
    "subjectMarathi": "भूगोल",
    "titleEnglish": "Geography Standard 7",
    "titleMarathi": "भूगोल इयत्ता ७",
    "descriptionEnglish": "Maharashtra State Board Geography Standard 7 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ भूगोल इयत्ता ७ पाठ्यपुस्तक",
    "fileName": "geogrpahy.pdf",
    "relativePath": "Books_Marathi_Medium/7th/geogrpahy.pdf",
    "driveId": "1dKNahqqOSOvJ6ENc2SKFs2Pz-zD3tcsu"
  },
  {
    "classNumber": 7,
    "medium": "marathi",
    "subjectEnglish": "Hindi",
    "subjectMarathi": "हिंदी",
    "titleEnglish": "Sugambharti Hindi Standard 7",
    "titleMarathi": "सुगमभारती हिंदी इयत्ता ७",
    "descriptionEnglish": "Maharashtra State Board Sugambharti Hindi Standard 7 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ सुगमभारती हिंदी इयत्ता ७ पाठ्यपुस्तक",
    "fileName": "hindi 2.pdf",
    "relativePath": "Books_Marathi_Medium/7th/hindi 2.pdf",
    "driveId": "1xTol8w4X8M98zEewvTVd7r3CPg5W2em-"
  },
  {
    "classNumber": 7,
    "medium": "marathi",
    "subjectEnglish": "Hindi",
    "subjectMarathi": "हिंदी",
    "titleEnglish": "Sulabhbharati Hindi Standard 7",
    "titleMarathi": "सुलभभारती हिंदी इयत्ता ७",
    "descriptionEnglish": "Maharashtra State Board Sulabhbharati Hindi Standard 7 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ सुलभभारती हिंदी इयत्ता ७ पाठ्यपुस्तक",
    "fileName": "hindi.pdf",
    "relativePath": "Books_Marathi_Medium/7th/hindi.pdf",
    "driveId": "1rzFAaAicTA6FJgbxDoitHENp1Q5D7o9m"
  },
  {
    "classNumber": 7,
    "medium": "marathi",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Balbharati Marathi Standard 7",
    "titleMarathi": "बालभारती मराठी इयत्ता ७",
    "descriptionEnglish": "Maharashtra State Board Balbharati Marathi Standard 7 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ बालभारती मराठी इयत्ता ७ पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_Marathi_Medium/7th/marathi.pdf",
    "driveId": "1Xt54tcGeKfxbIaFOGB8QhdAb-Pgl352C"
  },
  {
    "classNumber": 7,
    "medium": "marathi",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Ganit Standard 7",
    "titleMarathi": "गणित इयत्ता ७",
    "descriptionEnglish": "Maharashtra State Board Ganit Standard 7 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित इयत्ता ७ पाठ्यपुस्तक",
    "fileName": "maths.pdf",
    "relativePath": "Books_Marathi_Medium/7th/maths.pdf",
    "driveId": "1Rf5zPkab9gn1EpYJ6gtsIjwV7RWbczzC"
  },
  {
    "classNumber": 7,
    "medium": "marathi",
    "subjectEnglish": "Science",
    "subjectMarathi": "सामान्य विज्ञान",
    "titleEnglish": "General Science Standard 7",
    "titleMarathi": "सामान्य विज्ञान इयत्ता ७",
    "descriptionEnglish": "Maharashtra State Board General Science Standard 7 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ सामान्य विज्ञान इयत्ता ७ पाठ्यपुस्तक",
    "fileName": "science.pdf",
    "relativePath": "Books_Marathi_Medium/7th/science.pdf",
    "driveId": "1mbPvWJinoo2W4DhrKC-o3VyZXYhCKLrR"
  },
  {
    "classNumber": 8,
    "medium": "marathi",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "My English Book Standard 8",
    "titleMarathi": "माय इंग्लिश बुक इयत्ता ८",
    "descriptionEnglish": "Maharashtra State Board My English Book Standard 8 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ माय इंग्लिश बुक इयत्ता ८ पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_Marathi_Medium/8th/english.pdf",
    "driveId": "1Vo_IntZyjsID0QVmjrHXmMkX5bhyz3dS"
  },
  {
    "classNumber": 8,
    "medium": "marathi",
    "subjectEnglish": "Geography",
    "subjectMarathi": "भूगोल",
    "titleEnglish": "Geography Standard 8",
    "titleMarathi": "भूगोल इयत्ता ८",
    "descriptionEnglish": "Maharashtra State Board Geography Standard 8 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ भूगोल इयत्ता ८ पाठ्यपुस्तक",
    "fileName": "geogrpahy.pdf",
    "relativePath": "Books_Marathi_Medium/8th/geogrpahy.pdf",
    "driveId": "1l7lweRfekzookOe_MqNzYMtaHop6L07L"
  },
  {
    "classNumber": 8,
    "medium": "marathi",
    "subjectEnglish": "Hindi",
    "subjectMarathi": "हिंदी",
    "titleEnglish": "Sulabhbharati Hindi Standard 8",
    "titleMarathi": "सुलभभारती हिंदी इयत्ता ८",
    "descriptionEnglish": "Maharashtra State Board Sulabhbharati Hindi Standard 8 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ सुलभभारती हिंदी इयत्ता ८ पाठ्यपुस्तक",
    "fileName": "hindi.pdf",
    "relativePath": "Books_Marathi_Medium/8th/hindi.pdf",
    "driveId": "1Is4Vc6MIDcNRznenpCS8sqIdrpfEtOka"
  },
  {
    "classNumber": 8,
    "medium": "marathi",
    "subjectEnglish": "History",
    "subjectMarathi": "इतिहास व नागरिकशास्त्र",
    "titleEnglish": "History and Civics Standard 8",
    "titleMarathi": "इतिहास व नागरिकशास्त्र इयत्ता ८",
    "descriptionEnglish": "Maharashtra State Board History and Civics Standard 8 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ इतिहास व नागरिकशास्त्र इयत्ता ८ पाठ्यपुस्तक",
    "fileName": "hist.pdf",
    "relativePath": "Books_Marathi_Medium/8th/hist.pdf",
    "driveId": "1TZyaUsX893ssbwQgG0lpbURvAE0picY4"
  },
  {
    "classNumber": 8,
    "medium": "marathi",
    "subjectEnglish": "History",
    "subjectMarathi": "इतिहास व नागरिकशास्त्र",
    "titleEnglish": "History and Civics Standard 8",
    "titleMarathi": "इतिहास व नागरिकशास्त्र इयत्ता ८",
    "descriptionEnglish": "Maharashtra State Board History and Civics Standard 8 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ इतिहास व नागरिकशास्त्र इयत्ता ८ पाठ्यपुस्तक",
    "fileName": "history.pdf",
    "relativePath": "Books_Marathi_Medium/8th/history.pdf",
    "driveId": "1YfrXDghSVj36NtNJR2wq_xj7h5Y0I8La"
  },
  {
    "classNumber": 8,
    "medium": "marathi",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Balbharati Marathi Standard 8",
    "titleMarathi": "बालभारती मराठी इयत्ता ८",
    "descriptionEnglish": "Maharashtra State Board Balbharati Marathi Standard 8 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ बालभारती मराठी इयत्ता ८ पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_Marathi_Medium/8th/marathi.pdf",
    "driveId": "14zRdimfTMhiD4ygZ115T4dgNfHHR3-H_"
  },
  {
    "classNumber": 8,
    "medium": "marathi",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Ganit Standard 8",
    "titleMarathi": "गणित इयत्ता ८",
    "descriptionEnglish": "Maharashtra State Board Ganit Standard 8 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित इयत्ता ८ पाठ्यपुस्तक",
    "fileName": "maths.pdf",
    "relativePath": "Books_Marathi_Medium/8th/maths.pdf",
    "driveId": "1VQ1dREURMyqZGQ0nOkgVMZxw-nMhkBkv"
  },
  {
    "classNumber": 8,
    "medium": "marathi",
    "subjectEnglish": "Sanskrit",
    "subjectMarathi": "संस्कृत",
    "titleEnglish": "Amod Sanskrit Standard 8",
    "titleMarathi": "आमोद संस्कृत इयत्ता ८",
    "descriptionEnglish": "Maharashtra State Board Amod Sanskrit Standard 8 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ आमोद संस्कृत इयत्ता ८ पाठ्यपुस्तक",
    "fileName": "sanskrit.pdf",
    "relativePath": "Books_Marathi_Medium/8th/sanskrit.pdf",
    "driveId": "1ScN00zPuC5x2aTeqFR8hekH-sNOA-MnU"
  },
  {
    "classNumber": 8,
    "medium": "marathi",
    "subjectEnglish": "Science",
    "subjectMarathi": "सामान्य विज्ञान",
    "titleEnglish": "General Science Standard 8",
    "titleMarathi": "सामान्य विज्ञान इयत्ता ८",
    "descriptionEnglish": "Maharashtra State Board General Science Standard 8 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ सामान्य विज्ञान इयत्ता ८ पाठ्यपुस्तक",
    "fileName": "science.pdf",
    "relativePath": "Books_Marathi_Medium/8th/science.pdf",
    "driveId": "1YIEbPQvqZ58wGb2MCxzqOCAtAKhmlD3E"
  },
  {
    "classNumber": 9,
    "medium": "marathi",
    "subjectEnglish": "Art Education",
    "subjectMarathi": "कला शिक्षण",
    "titleEnglish": "Art Education Standard 9",
    "titleMarathi": "कला शिक्षण इयत्ता ९",
    "descriptionEnglish": "Maharashtra State Board Art Education Standard 9 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ कला शिक्षण इयत्ता ९ पाठ्यपुस्तक",
    "fileName": "kala.pdf",
    "relativePath": "Books_Marathi_Medium/9th/kala.pdf",
    "driveId": "1wSPI0ZI5qeiF4cR0FD5nGcdbZJWaDFMe"
  },
  {
    "classNumber": 9,
    "medium": "marathi",
    "subjectEnglish": "Defence Studies",
    "subjectMarathi": "संरक्षण शास्त्र",
    "titleEnglish": "Defence Studies Standard 9",
    "titleMarathi": "संरक्षण शास्त्र इयत्ता ९",
    "descriptionEnglish": "Maharashtra State Board Defence Studies Standard 9 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ संरक्षण शास्त्र इयत्ता ९ पाठ्यपुस्तक",
    "fileName": "forces.pdf",
    "relativePath": "Books_Marathi_Medium/9th/forces.pdf",
    "driveId": "1hpupUJJOv_7-ZJNEUk7YspoUwqt6Z222"
  },
  {
    "classNumber": 9,
    "medium": "marathi",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "My English Coursebook Standard 9",
    "titleMarathi": "माय इंग्लिश कोर्सबुक इयत्ता ९",
    "descriptionEnglish": "Maharashtra State Board My English Coursebook Standard 9 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ माय इंग्लिश कोर्सबुक इयत्ता ९ पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_Marathi_Medium/9th/english.pdf",
    "driveId": "1pKEZ19WClDzPUs6sy5kIaB8vKXm1clJq"
  },
  {
    "classNumber": 9,
    "medium": "marathi",
    "subjectEnglish": "Geography",
    "subjectMarathi": "भूगोल",
    "titleEnglish": "Geography Standard 9",
    "titleMarathi": "भूगोल इयत्ता ९",
    "descriptionEnglish": "Maharashtra State Board Geography Standard 9 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ भूगोल इयत्ता ९ पाठ्यपुस्तक",
    "fileName": "geography.pdf",
    "relativePath": "Books_Marathi_Medium/9th/geography.pdf",
    "driveId": "19okYEdZzhhBBbL_VTB3jLIQDiZrVnT4N"
  },
  {
    "classNumber": 9,
    "medium": "marathi",
    "subjectEnglish": "Hindi",
    "subjectMarathi": "हिंदी",
    "titleEnglish": "Lokbharati Hindi Standard 9",
    "titleMarathi": "लोकभारती हिंदी इयत्ता ९",
    "descriptionEnglish": "Maharashtra State Board Lokbharati Hindi Standard 9 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ लोकभारती हिंदी इयत्ता ९ पाठ्यपुस्तक",
    "fileName": "hindi.pdf",
    "relativePath": "Books_Marathi_Medium/9th/hindi.pdf",
    "driveId": "1oZ5IaLtUCTJRi_m5JMzx9uzkSlsF_pES"
  },
  {
    "classNumber": 9,
    "medium": "marathi",
    "subjectEnglish": "History",
    "subjectMarathi": "इतिहास व राज्यशास्त्र",
    "titleEnglish": "History and Political Science Standard 9",
    "titleMarathi": "इतिहास व राज्यशास्त्र इयत्ता ९",
    "descriptionEnglish": "Maharashtra State Board History and Political Science Standard 9 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ इतिहास व राज्यशास्त्र इयत्ता ९ पाठ्यपुस्तक",
    "fileName": "history.pdf",
    "relativePath": "Books_Marathi_Medium/9th/history.pdf",
    "driveId": "1lT0vtjBuBIPxOu0vmPjKplexpyfkSpz9"
  },
  {
    "classNumber": 9,
    "medium": "marathi",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Kumarbharati Marathi Standard 9",
    "titleMarathi": "कुमारभारती मराठी इयत्ता ९",
    "descriptionEnglish": "Maharashtra State Board Kumarbharati Marathi Standard 9 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ कुमारभारती मराठी इयत्ता ९ पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_Marathi_Medium/9th/marathi.pdf",
    "driveId": "1-Ovl3qi-3zXUbGzjSNUrMdTru8mCJo-f"
  },
  {
    "classNumber": 9,
    "medium": "marathi",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Mathematics Part 1 (Algebra) Standard 9",
    "titleMarathi": "गणित भाग १ (बीजगणित) इयत्ता ९",
    "descriptionEnglish": "Maharashtra State Board Mathematics Part 1 (Algebra) Standard 9 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित भाग १ (बीजगणित) इयत्ता ९ पाठ्यपुस्तक",
    "fileName": "maths 1.pdf",
    "relativePath": "Books_Marathi_Medium/9th/maths 1.pdf",
    "driveId": "1RWkQ7gyZbs1QxdXcpkRj9Jmz4o5IdPea"
  },
  {
    "classNumber": 9,
    "medium": "marathi",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Mathematics Part 2 (Geometry) Standard 9",
    "titleMarathi": "गणित भाग २ (भूमिती) इयत्ता ९",
    "descriptionEnglish": "Maharashtra State Board Mathematics Part 2 (Geometry) Standard 9 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित भाग २ (भूमिती) इयत्ता ९ पाठ्यपुस्तक",
    "fileName": "maths 2.pdf",
    "relativePath": "Books_Marathi_Medium/9th/maths 2.pdf",
    "driveId": "1GJIYxSQY8uOO6m_1o_SEkdSa7S3VRHh7"
  },
  {
    "classNumber": 9,
    "medium": "marathi",
    "subjectEnglish": "Sanskrit",
    "subjectMarathi": "संस्कृत",
    "titleEnglish": "Amod Sanskrit Standard 9",
    "titleMarathi": "आमोद संस्कृत इयत्ता ९",
    "descriptionEnglish": "Maharashtra State Board Amod Sanskrit Standard 9 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ आमोद संस्कृत इयत्ता ९ पाठ्यपुस्तक",
    "fileName": "sanskrit.pdf",
    "relativePath": "Books_Marathi_Medium/9th/sanskrit.pdf",
    "driveId": "1ctxATGVBs0W7JT7GZTx2wYLhhEyR8S1A"
  },
  {
    "classNumber": 9,
    "medium": "marathi",
    "subjectEnglish": "Sanskrit",
    "subjectMarathi": "संस्कृत",
    "titleEnglish": "Anand Sanskrit Standard 9",
    "titleMarathi": "आनंद संस्कृत इयत्ता ९",
    "descriptionEnglish": "Maharashtra State Board Anand Sanskrit Standard 9 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ आनंद संस्कृत इयत्ता ९ पाठ्यपुस्तक",
    "fileName": "snaksrit 2.pdf",
    "relativePath": "Books_Marathi_Medium/9th/snaksrit 2.pdf",
    "driveId": "1kXoxAkj_4CWvoXsSmrhK-1wtA9dn71Id"
  },
  {
    "classNumber": 9,
    "medium": "marathi",
    "subjectEnglish": "Science",
    "subjectMarathi": "विज्ञान आणि तंत्रज्ञान",
    "titleEnglish": "Science and Technology Part 1 Standard 9",
    "titleMarathi": "विज्ञान आणि तंत्रज्ञान भाग १ इयत्ता ९",
    "descriptionEnglish": "Maharashtra State Board Science and Technology Part 1 Standard 9 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ विज्ञान आणि तंत्रज्ञान भाग १ इयत्ता ९ पाठ्यपुस्तक",
    "fileName": "science1.pdf",
    "relativePath": "Books_Marathi_Medium/9th/science1.pdf",
    "driveId": "10EQs73QPRe6aiEJXF2IKyJ-vPnhKBeAG"
  },
  {
    "classNumber": 9,
    "medium": "marathi",
    "subjectEnglish": "Water Security",
    "subjectMarathi": "जलसुरक्षा",
    "titleEnglish": "Water Security Standard 9",
    "titleMarathi": "जलसुरक्षा इयत्ता ९",
    "descriptionEnglish": "Maharashtra State Board Water Security Standard 9 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ जलसुरक्षा इयत्ता ९ पाठ्यपुस्तक",
    "fileName": "water reservior.pdf",
    "relativePath": "Books_Marathi_Medium/9th/water reservior.pdf",
    "driveId": "1D-Mf_0G2nC1t4HGw87-WgKifncYy_GiR"
  },
  {
    "classNumber": 10,
    "medium": "marathi",
    "subjectEnglish": "Defence Studies",
    "subjectMarathi": "संरक्षण शास्त्र",
    "titleEnglish": "Defence Studies Standard 10",
    "titleMarathi": "संरक्षण शास्त्र इयत्ता १०",
    "descriptionEnglish": "Maharashtra State Board Defence Studies Standard 10 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ संरक्षण शास्त्र इयत्ता १० पाठ्यपुस्तक",
    "fileName": "defence.pdf",
    "relativePath": "Books_Marathi_Medium/10th/defence.pdf",
    "driveId": "1fhfUMaXAvH94KGq7aScU82VVbzdbRzy6"
  },
  {
    "classNumber": 10,
    "medium": "marathi",
    "subjectEnglish": "English",
    "subjectMarathi": "इंग्रजी",
    "titleEnglish": "My English Coursebook Standard 10",
    "titleMarathi": "माय इंग्लिश कोर्सबुक इयत्ता १०",
    "descriptionEnglish": "Maharashtra State Board My English Coursebook Standard 10 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ माय इंग्लिश कोर्सबुक इयत्ता १० पाठ्यपुस्तक",
    "fileName": "english.pdf",
    "relativePath": "Books_Marathi_Medium/10th/english.pdf",
    "driveId": "1UVQcet7KrbfoEgms87albdx_ftUbS3I3"
  },
  {
    "classNumber": 10,
    "medium": "marathi",
    "subjectEnglish": "Geography",
    "subjectMarathi": "भूगोल",
    "titleEnglish": "Geography Standard 10",
    "titleMarathi": "भूगोल इयत्ता १०",
    "descriptionEnglish": "Maharashtra State Board Geography Standard 10 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ भूगोल इयत्ता १० पाठ्यपुस्तक",
    "fileName": "geography.pdf",
    "relativePath": "Books_Marathi_Medium/10th/geography.pdf",
    "driveId": "1vlFy7PIVZjAGbj4AD4VMrWYi-xJxPDgs"
  },
  {
    "classNumber": 10,
    "medium": "marathi",
    "subjectEnglish": "Hindi",
    "subjectMarathi": "हिंदी",
    "titleEnglish": "Lokbharati Hindi Standard 10",
    "titleMarathi": "लोकभारती हिंदी इयत्ता १०",
    "descriptionEnglish": "Maharashtra State Board Lokbharati Hindi Standard 10 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ लोकभारती हिंदी इयत्ता १० पाठ्यपुस्तक",
    "fileName": "hindi.pdf",
    "relativePath": "Books_Marathi_Medium/10th/hindi.pdf",
    "driveId": "178wS0WNvMf_elswquHGAoTUoAKyM1I0m"
  },
  {
    "classNumber": 10,
    "medium": "marathi",
    "subjectEnglish": "History",
    "subjectMarathi": "इतिहास व राज्यशास्त्र",
    "titleEnglish": "History and Political Science Standard 10",
    "titleMarathi": "इतिहास व राज्यशास्त्र इयत्ता १०",
    "descriptionEnglish": "Maharashtra State Board History and Political Science Standard 10 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ इतिहास व राज्यशास्त्र इयत्ता १० पाठ्यपुस्तक",
    "fileName": "history.pdf",
    "relativePath": "Books_Marathi_Medium/10th/history.pdf",
    "driveId": "1vlcnl5y34d5AtQniIh7VEpJxMidcG5Ev"
  },
  {
    "classNumber": 10,
    "medium": "marathi",
    "subjectEnglish": "Marathi",
    "subjectMarathi": "मराठी",
    "titleEnglish": "Kumarbharati Marathi Standard 10",
    "titleMarathi": "कुमारभारती मराठी इयत्ता १०",
    "descriptionEnglish": "Maharashtra State Board Kumarbharati Marathi Standard 10 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ कुमारभारती मराठी इयत्ता १० पाठ्यपुस्तक",
    "fileName": "marathi.pdf",
    "relativePath": "Books_Marathi_Medium/10th/marathi.pdf",
    "driveId": "1XApwMaJbZAN1sN3-SNxlI5bAA4u5mdvX"
  },
  {
    "classNumber": 10,
    "medium": "marathi",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Mathematics Part 1 (Algebra) Standard 10",
    "titleMarathi": "गणित भाग १ (बीजगणित) इयत्ता १०",
    "descriptionEnglish": "Maharashtra State Board Mathematics Part 1 (Algebra) Standard 10 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित भाग १ (बीजगणित) इयत्ता १० पाठ्यपुस्तक",
    "fileName": "maths 1.pdf",
    "relativePath": "Books_Marathi_Medium/10th/maths 1.pdf",
    "driveId": "1oF2goh9p8pZDHTZW_H0VnULzAheKdzmY"
  },
  {
    "classNumber": 10,
    "medium": "marathi",
    "subjectEnglish": "Mathematics",
    "subjectMarathi": "गणित",
    "titleEnglish": "Mathematics Part 2 (Geometry) Standard 10",
    "titleMarathi": "गणित भाग २ (भूमिती) इयत्ता १०",
    "descriptionEnglish": "Maharashtra State Board Mathematics Part 2 (Geometry) Standard 10 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ गणित भाग २ (भूमिती) इयत्ता १० पाठ्यपुस्तक",
    "fileName": "maths 2.pdf",
    "relativePath": "Books_Marathi_Medium/10th/maths 2.pdf",
    "driveId": "1eEbLmTmu1oPf4bQ9-AJppkXKLI5wMhWW"
  },
  {
    "classNumber": 10,
    "medium": "marathi",
    "subjectEnglish": "Sanskrit",
    "subjectMarathi": "संस्कृत",
    "titleEnglish": "Amod Sanskrit Standard 10",
    "titleMarathi": "आमोद संस्कृत इयत्ता १०",
    "descriptionEnglish": "Maharashtra State Board Amod Sanskrit Standard 10 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ आमोद संस्कृत इयत्ता १० पाठ्यपुस्तक",
    "fileName": "sanskrit.pdf",
    "relativePath": "Books_Marathi_Medium/10th/sanskrit.pdf",
    "driveId": "1Auws1v2CXNZpoJ3NbKcFML18wbJ9EDsO"
  },
  {
    "classNumber": 10,
    "medium": "marathi",
    "subjectEnglish": "Science",
    "subjectMarathi": "विज्ञान आणि तंत्रज्ञान",
    "titleEnglish": "Science and Technology Part 1 Standard 10",
    "titleMarathi": "विज्ञान आणि तंत्रज्ञान भाग १ इयत्ता १०",
    "descriptionEnglish": "Maharashtra State Board Science and Technology Part 1 Standard 10 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ विज्ञान आणि तंत्रज्ञान भाग १ इयत्ता १० पाठ्यपुस्तक",
    "fileName": "science 1.pdf",
    "relativePath": "Books_Marathi_Medium/10th/science 1.pdf",
    "driveId": "13kJ5RLuORJ-nBoKHb0aeO84sHiVW0xN4"
  },
  {
    "classNumber": 10,
    "medium": "marathi",
    "subjectEnglish": "Science",
    "subjectMarathi": "विज्ञान आणि तंत्रज्ञान",
    "titleEnglish": "Science and Technology Part 2 Standard 10",
    "titleMarathi": "विज्ञान आणि तंत्रज्ञान भाग २ इयत्ता १०",
    "descriptionEnglish": "Maharashtra State Board Science and Technology Part 2 Standard 10 textbook",
    "descriptionMarathi": "महाराष्ट्र राज्य मंडळ विज्ञान आणि तंत्रज्ञान भाग २ इयत्ता १० पाठ्यपुस्तक",
    "fileName": "science 2.pdf",
    "relativePath": "Books_Marathi_Medium/10th/science 2.pdf",
    "driveId": "1-xa-c7ibqnzpBDmFgdK7f5Iaxzmw1hM7"
  }
];
