// src/database/seeders/textbookPdfsData.ts

export interface TextbookPdfSeed {
  classNumber: number;
  medium: 'english' | 'marathi';
  subjectEnglish: string;
  subjectMarathi: string;
  titleEnglish: string;
  titleMarathi: string;
  descriptionEnglish: string;
  descriptionMarathi: string;
  fileName: string;
  relativePath: string;
}

export const textbookPdfs: TextbookPdfSeed[] = [
  // ============================================================
  // CLASS 1
  // ============================================================
  // English Medium
  {
    classNumber: 1,
    medium: 'english',
    subjectEnglish: 'English',
    subjectMarathi: 'इंग्रजी',
    titleEnglish: 'Balbharati English Standard 1',
    titleMarathi: 'बालभारती इंग्रजी इयत्ता १',
    descriptionEnglish: 'Maharashtra State Board Balbharati English textbook for Class 1',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ बालभारती इंग्रजी पाठ्यपुस्तक इयत्ता १',
    fileName: 'Balbharati.pdf',
    relativePath: '1st Std/English Medium/Balbharati.pdf',
  },
  {
    classNumber: 1,
    medium: 'english',
    subjectEnglish: 'Mathematics',
    subjectMarathi: 'गणित',
    titleEnglish: 'Mathematics Standard 1',
    titleMarathi: 'गणित इयत्ता १',
    descriptionEnglish: 'Maharashtra State Board Mathematics textbook for Class 1',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ गणित पाठ्यपुस्तक इयत्ता १',
    fileName: 'math.pdf',
    relativePath: '1st Std/English Medium/math.pdf',
  },
  {
    classNumber: 1,
    medium: 'english',
    subjectEnglish: 'Marathi',
    subjectMarathi: 'मराठी',
    titleEnglish: 'Shiku Marathi Anandane Standard 1',
    titleMarathi: 'शिका मराठी आनंदाने इयत्ता १',
    descriptionEnglish: 'Maharashtra State Board Shiku Marathi Anandane for Class 1',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ शिका मराठी आनंदाने इयत्ता १',
    fileName: 'shiku marathi anandane.pdf',
    relativePath: '1st Std/English Medium/shiku marathi anandane.pdf',
  },
  // Marathi Medium
  {
    classNumber: 1,
    medium: 'marathi',
    subjectEnglish: 'Marathi',
    subjectMarathi: 'मराठी',
    titleEnglish: 'Balbharati Marathi Standard 1',
    titleMarathi: 'बालभारती मराठी इयत्ता १',
    descriptionEnglish: 'Maharashtra State Board Balbharati Marathi textbook for Class 1',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ बालभारती मराठी पाठ्यपुस्तक इयत्ता १',
    fileName: 'Balbharati.pdf',
    relativePath: '1st Std/Marathi medium/Balbharati.pdf',
  },
  {
    classNumber: 1,
    medium: 'marathi',
    subjectEnglish: 'English',
    subjectMarathi: 'इंग्रजी',
    titleEnglish: 'My English Book Standard 1',
    titleMarathi: 'माय इंग्लिश बुक इयत्ता १',
    descriptionEnglish: 'Maharashtra State Board English textbook for Class 1 (Marathi Medium)',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ इंग्रजी पाठ्यपुस्तक इयत्ता १ (मराठी माध्यम)',
    fileName: 'english.pdf',
    relativePath: '1st Std/Marathi medium/english.pdf',
  },
  {
    classNumber: 1,
    medium: 'marathi',
    subjectEnglish: 'Mathematics',
    subjectMarathi: 'गणित',
    titleEnglish: 'Ganit Standard 1',
    titleMarathi: 'गणित इयत्ता १',
    descriptionEnglish: 'Maharashtra State Board Ganit textbook for Class 1',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ गणित पाठ्यपुस्तक इयत्ता १',
    fileName: 'math.pdf',
    relativePath: '1st Std/Marathi medium/math.pdf',
  },

  // ============================================================
  // CLASS 2
  // ============================================================
  // English Medium
  {
    classNumber: 2,
    medium: 'english',
    subjectEnglish: 'English',
    subjectMarathi: 'इंग्रजी',
    titleEnglish: 'Balbharati English Standard 2',
    titleMarathi: 'बालभारती इंग्रजी इयत्ता २',
    descriptionEnglish: 'Maharashtra State Board Balbharati English textbook for Class 2',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ बालभारती इंग्रजी पाठ्यपुस्तक इयत्ता २',
    fileName: 'balbharati.pdf',
    relativePath: '2nd Std/English Medium/balbharati.pdf',
  },
  {
    classNumber: 2,
    medium: 'english',
    subjectEnglish: 'English',
    subjectMarathi: 'इंग्रजी',
    titleEnglish: 'English Reader Standard 2',
    titleMarathi: 'इंग्रजी वाचन पुस्तक इयत्ता २',
    descriptionEnglish: 'Maharashtra State Board English Reader for Class 2',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ इंग्रजी वाचन पुस्तक इयत्ता २',
    fileName: 'english.pdf',
    relativePath: '2nd Std/English Medium/english.pdf',
  },
  {
    classNumber: 2,
    medium: 'english',
    subjectEnglish: 'Mathematics',
    subjectMarathi: 'गणित',
    titleEnglish: 'Mathematics Standard 2',
    titleMarathi: 'गणित इयत्ता २',
    descriptionEnglish: 'Maharashtra State Board Mathematics textbook for Class 2',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ गणित पाठ्यपुस्तक इयत्ता २',
    fileName: 'math.pdf',
    relativePath: '2nd Std/English Medium/math.pdf',
  },
  {
    classNumber: 2,
    medium: 'english',
    subjectEnglish: 'Play, Do, Learn',
    subjectMarathi: 'खेळू, करू, शिकू',
    titleEnglish: 'Play, Do, Learn Standard 2',
    titleMarathi: 'खेळू, करू, शिकू इयत्ता २',
    descriptionEnglish: 'Maharashtra State Board Play, Do, Learn textbook for Class 2',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ खेळू, करू, शिकू पाठ्यपुस्तक इयत्ता २',
    fileName: 'paly do learn.pdf',
    relativePath: '2nd Std/English Medium/paly do learn.pdf',
  },
  // Marathi Medium
  {
    classNumber: 2,
    medium: 'marathi',
    subjectEnglish: 'English',
    subjectMarathi: 'इंग्रजी',
    titleEnglish: 'My English Book Standard 2',
    titleMarathi: 'माय इंग्लिश बुक इयत्ता २',
    descriptionEnglish: 'Maharashtra State Board English textbook for Class 2 (Marathi Medium)',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ इंग्रजी पाठ्यपुस्तक इयत्ता २ (मराठी माध्यम)',
    fileName: 'english.pdf',
    relativePath: '2nd Std/Marathi Medium/english.pdf',
  },
  {
    classNumber: 2,
    medium: 'marathi',
    subjectEnglish: 'Play, Do, Learn',
    subjectMarathi: 'खेळू, करू, शिकू',
    titleEnglish: 'Khel Karu Shiku Standard 2',
    titleMarathi: 'खेळू, करू, शिकू इयत्ता २',
    descriptionEnglish: 'Maharashtra State Board Khel Karu Shiku textbook for Class 2',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ खेळू, करू, शिकू पाठ्यपुस्तक इयत्ता २',
    fileName: 'khel karu shiku.pdf',
    relativePath: '2nd Std/Marathi Medium/khel karu shiku.pdf',
  },
  {
    classNumber: 2,
    medium: 'marathi',
    subjectEnglish: 'Marathi',
    subjectMarathi: 'मराठी',
    titleEnglish: 'Balbharati Marathi Standard 2',
    titleMarathi: 'बालभारती मराठी इयत्ता २',
    descriptionEnglish: 'Maharashtra State Board Balbharati Marathi textbook for Class 2',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ बालभारती मराठी पाठ्यपुस्तक इयत्ता २',
    fileName: 'marathi.pdf',
    relativePath: '2nd Std/Marathi Medium/marathi.pdf',
  },
  {
    classNumber: 2,
    medium: 'marathi',
    subjectEnglish: 'Mathematics',
    subjectMarathi: 'गणित',
    titleEnglish: 'Ganit Standard 2',
    titleMarathi: 'गणित इयत्ता २',
    descriptionEnglish: 'Maharashtra State Board Ganit textbook for Class 2',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ गणित पाठ्यपुस्तक इयत्ता २',
    fileName: 'math.pdf',
    relativePath: '2nd Std/Marathi Medium/math.pdf',
  },

  // ============================================================
  // CLASS 3
  // ============================================================
  // English Medium
  {
    classNumber: 3,
    medium: 'english',
    subjectEnglish: 'English',
    subjectMarathi: 'इंग्रजी',
    titleEnglish: 'Balbharati English Standard 3',
    titleMarathi: 'बालभारती इंग्रजी इयत्ता ३',
    descriptionEnglish: 'Maharashtra State Board Balbharati English textbook for Class 3',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ बालभारती इंग्रजी पाठ्यपुस्तक इयत्ता ३',
    fileName: 'balbharati.pdf',
    relativePath: '3rd Std/English Medium/balbharati.pdf',
  },
  {
    classNumber: 3,
    medium: 'english',
    subjectEnglish: 'English',
    subjectMarathi: 'इंग्रजी',
    titleEnglish: 'English Reader Standard 3',
    titleMarathi: 'इंग्रजी वाचन पुस्तक इयत्ता ३',
    descriptionEnglish: 'Maharashtra State Board English Reader for Class 3',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ इंग्रजी वाचन पुस्तक इयत्ता ३',
    fileName: 'english.pdf',
    relativePath: '3rd Std/English Medium/english.pdf',
  },
  {
    classNumber: 3,
    medium: 'english',
    subjectEnglish: 'Environmental Studies',
    subjectMarathi: 'परिसर अभ्यास',
    titleEnglish: 'Environmental Studies Standard 3',
    titleMarathi: 'परिसर अभ्यास इयत्ता ३',
    descriptionEnglish: 'Maharashtra State Board Environmental Studies textbook for Class 3',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ परिसर अभ्यास पाठ्यपुस्तक इयत्ता ३',
    fileName: 'enviornmental studies.pdf',
    relativePath: '3rd Std/English Medium/enviornmental studies.pdf',
  },
  {
    classNumber: 3,
    medium: 'english',
    subjectEnglish: 'Mathematics',
    subjectMarathi: 'गणित',
    titleEnglish: 'Mathematics Standard 3',
    titleMarathi: 'गणित इयत्ता ३',
    descriptionEnglish: 'Maharashtra State Board Mathematics textbook for Class 3',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ गणित पाठ्यपुस्तक इयत्ता ३',
    fileName: 'math.pdf',
    relativePath: '3rd Std/English Medium/math.pdf',
  },
  {
    classNumber: 3,
    medium: 'english',
    subjectEnglish: 'Play, Do, Learn',
    subjectMarathi: 'खेळू, करू, शिकू',
    titleEnglish: 'Play, Do, Learn Standard 3',
    titleMarathi: 'खेळू, करू, शिकू इयत्ता ३',
    descriptionEnglish: 'Maharashtra State Board Play, Do, Learn textbook for Class 3',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ खेळू, करू, शिकू पाठ्यपुस्तक इयत्ता ३',
    fileName: 'play do learn.pdf',
    relativePath: '3rd Std/English Medium/play do learn.pdf',
  },
  {
    classNumber: 3,
    medium: 'english',
    subjectEnglish: 'Marathi',
    subjectMarathi: 'मराठी',
    titleEnglish: 'Sulabhbharati Marathi Standard 3',
    titleMarathi: 'सुलभभारती मराठी इयत्ता ३',
    descriptionEnglish: 'Maharashtra State Board Sulabhbharati Marathi for Class 3',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ सुलभभारती मराठी पाठ्यपुस्तक इयत्ता ३',
    fileName: 'sulbhbharti.pdf',
    relativePath: '3rd Std/English Medium/sulbhbharti.pdf',
  },
  // Marathi Medium
  {
    classNumber: 3,
    medium: 'marathi',
    subjectEnglish: 'English',
    subjectMarathi: 'इंग्रजी',
    titleEnglish: 'My English Book Standard 3',
    titleMarathi: 'माय इंग्लिश बुक इयत्ता ३',
    descriptionEnglish: 'Maharashtra State Board English textbook for Class 3 (Marathi Medium)',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ इंग्रजी पाठ्यपुस्तक इयत्ता ३ (मराठी माध्यम)',
    fileName: 'english.pdf',
    relativePath: '3rd Std/Marathi Medium/english.pdf',
  },
  {
    classNumber: 3,
    medium: 'marathi',
    subjectEnglish: 'Environmental Studies',
    subjectMarathi: 'परिसर अभ्यास',
    titleEnglish: 'Parisar Abhyas Standard 3',
    titleMarathi: 'परिसर अभ्यास इयत्ता ३',
    descriptionEnglish: 'Maharashtra State Board Parisar Abhyas textbook for Class 3',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ परिसर अभ्यास पाठ्यपुस्तक इयत्ता ३',
    fileName: 'enviornmental studies.pdf',
    relativePath: '3rd Std/Marathi Medium/enviornmental studies.pdf',
  },
  {
    classNumber: 3,
    medium: 'marathi',
    subjectEnglish: 'Play, Do, Learn',
    subjectMarathi: 'खेळू, करू, शिकू',
    titleEnglish: 'Khelu Karu Shiku Standard 3',
    titleMarathi: 'खेळू, करू, शिकू इयत्ता ३',
    descriptionEnglish: 'Maharashtra State Board Khelu Karu Shiku textbook for Class 3',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ खेळू, करू, शिकू पाठ्यपुस्तक इयत्ता ३',
    fileName: 'khelu karu shiku.pdf',
    relativePath: '3rd Std/Marathi Medium/khelu karu shiku.pdf',
  },
  {
    classNumber: 3,
    medium: 'marathi',
    subjectEnglish: 'Marathi',
    subjectMarathi: 'मराठी',
    titleEnglish: 'Balbharati Marathi Standard 3',
    titleMarathi: 'बालभारती मराठी इयत्ता ३',
    descriptionEnglish: 'Maharashtra State Board Balbharati Marathi textbook for Class 3',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ बालभारती मराठी पाठ्यपुस्तक इयत्ता ३',
    fileName: 'marathi.pdf',
    relativePath: '3rd Std/Marathi Medium/marathi.pdf',
  },
  {
    classNumber: 3,
    medium: 'marathi',
    subjectEnglish: 'Mathematics',
    subjectMarathi: 'गणित',
    titleEnglish: 'Ganit Standard 3',
    titleMarathi: 'गणित इयत्ता ३',
    descriptionEnglish: 'Maharashtra State Board Ganit textbook for Class 3',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ गणित पाठ्यपुस्तक इयत्ता ३',
    fileName: 'math.pdf',
    relativePath: '3rd Std/Marathi Medium/math.pdf',
  },
  {
    classNumber: 3,
    medium: 'marathi',
    subjectEnglish: 'Hindi',
    subjectMarathi: 'हिंदी',
    titleEnglish: 'Sulabhbharati Hindi Standard 3',
    titleMarathi: 'सुलभभारती हिंदी इयत्ता ३',
    descriptionEnglish: 'Maharashtra State Board Sulabhbharati Hindi for Class 3',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ सुलभभारती हिंदी पाठ्यपुस्तक इयत्ता ३',
    fileName: 'sulbhbharti.pdf',
    relativePath: '3rd Std/Marathi Medium/sulbhbharti.pdf',
  },

  // ============================================================
  // CLASS 4
  // ============================================================
  // English Medium
  {
    classNumber: 4,
    medium: 'english',
    subjectEnglish: 'English',
    subjectMarathi: 'इंग्रजी',
    titleEnglish: 'Balbharati English Standard 4',
    titleMarathi: 'बालभारती इंग्रजी इयत्ता ४',
    descriptionEnglish: 'Maharashtra State Board Balbharati English textbook for Class 4',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ बालभारती इंग्रजी पाठ्यपुस्तक इयत्ता ४',
    fileName: 'balbharati.pdf',
    relativePath: '4rth Std/English Medium/balbharati.pdf',
  },
  {
    classNumber: 4,
    medium: 'english',
    subjectEnglish: 'English',
    subjectMarathi: 'इंग्रजी',
    titleEnglish: 'English Reader Standard 4',
    titleMarathi: 'इंग्रजी वाचन पुस्तक इयत्ता ४',
    descriptionEnglish: 'Maharashtra State Board English Reader for Class 4',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ इंग्रजी वाचन पुस्तक इयत्ता ४',
    fileName: 'english.pdf',
    relativePath: '4rth Std/English Medium/english.pdf',
  },
  {
    classNumber: 4,
    medium: 'english',
    subjectEnglish: 'Environmental Studies',
    subjectMarathi: 'परिसर अभ्यास',
    titleEnglish: 'Environmental Studies Part 1 Standard 4',
    titleMarathi: 'परिसर अभ्यास भाग १ इयत्ता ४',
    descriptionEnglish: 'Maharashtra State Board Environmental Studies Part 1 for Class 4',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ परिसर अभ्यास भाग १ पाठ्यपुस्तक इयत्ता ४',
    fileName: 'enviornmental studies part-1.pdf',
    relativePath: '4rth Std/English Medium/enviornmental studies part-1.pdf',
  },
  {
    classNumber: 4,
    medium: 'english',
    subjectEnglish: 'Environmental Studies',
    subjectMarathi: 'परिसर अभ्यास',
    titleEnglish: 'Environmental Studies Part 2 (History) Standard 4',
    titleMarathi: 'परिसर अभ्यास भाग २ (इतिहास) इयत्ता ४',
    descriptionEnglish: 'Maharashtra State Board Environmental Studies Part 2 (Chhatrapati Shivaji Maharaj) for Class 4',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ परिसर अभ्यास भाग २ (छत्रपती शिवाजी महाराज) पाठ्यपुस्तक इयत्ता ४',
    fileName: 'enviornmental studies part-2.pdf',
    relativePath: '4rth Std/English Medium/enviornmental studies part-2.pdf',
  },
  {
    classNumber: 4,
    medium: 'english',
    subjectEnglish: 'Mathematics',
    subjectMarathi: 'गणित',
    titleEnglish: 'Mathematics Standard 4',
    titleMarathi: 'गणित इयत्ता ४',
    descriptionEnglish: 'Maharashtra State Board Mathematics textbook for Class 4',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ गणित पाठ्यपुस्तक इयत्ता ४',
    fileName: 'mathematics.pdf',
    relativePath: '4rth Std/English Medium/mathematics.pdf',
  },
  {
    classNumber: 4,
    medium: 'english',
    subjectEnglish: 'Play, Do, Learn',
    subjectMarathi: 'खेळू, करू, शिकू',
    titleEnglish: 'Play, Do, Learn Standard 4',
    titleMarathi: 'खेळू, करू, शिकू इयत्ता ४',
    descriptionEnglish: 'Maharashtra State Board Play, Do, Learn textbook for Class 4',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ खेळू, करू, शिकू पाठ्यपुस्तक इयत्ता ४',
    fileName: 'play do learn.pdf',
    relativePath: '4rth Std/English Medium/play do learn.pdf',
  },
  {
    classNumber: 4,
    medium: 'english',
    subjectEnglish: 'Marathi',
    subjectMarathi: 'मराठी',
    titleEnglish: 'Sulabhbharati Marathi Standard 4',
    titleMarathi: 'सुलभभारती मराठी इयत्ता ४',
    descriptionEnglish: 'Maharashtra State Board Sulabhbharati Marathi for Class 4',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ सुलभभारती मराठी पाठ्यपुस्तक इयत्ता ४',
    fileName: 'सुलभभारती.pdf',
    relativePath: '4rth Std/English Medium/सुलभभारती.pdf',
  },
  // Marathi Medium
  {
    classNumber: 4,
    medium: 'marathi',
    subjectEnglish: 'English',
    subjectMarathi: 'इंग्रजी',
    titleEnglish: 'My English Book Standard 4',
    titleMarathi: 'माय इंग्लिश बुक इयत्ता ४',
    descriptionEnglish: 'Maharashtra State Board English textbook for Class 4 (Marathi Medium)',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ इंग्रजी पाठ्यपुस्तक इयत्ता ४ (मराठी माध्यम)',
    fileName: 'english.pdf',
    relativePath: '4rth Std/Marathi medium/english.pdf',
  },
  {
    classNumber: 4,
    medium: 'marathi',
    subjectEnglish: 'Play, Do, Learn',
    subjectMarathi: 'खेळू, करू, शिकू',
    titleEnglish: 'Khelu, Karu, Shiku Standard 4',
    titleMarathi: 'खेळू, करू, शिकू इयत्ता ४',
    descriptionEnglish: 'Maharashtra State Board Khelu, Karu, Shiku textbook for Class 4',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ खेळू, करू, शिकू पाठ्यपुस्तक इयत्ता ४',
    fileName: 'खेळू, करू, शिकू.pdf',
    relativePath: '4rth Std/Marathi medium/खेळू, करू, शिकू.pdf',
  },
  {
    classNumber: 4,
    medium: 'marathi',
    subjectEnglish: 'Mathematics',
    subjectMarathi: 'गणित',
    titleEnglish: 'Ganit Standard 4',
    titleMarathi: 'गणित इयत्ता ४',
    descriptionEnglish: 'Maharashtra State Board Ganit textbook for Class 4',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ गणित पाठ्यपुस्तक इयत्ता ४',
    fileName: 'गणित.pdf',
    relativePath: '4rth Std/Marathi medium/गणित.pdf',
  },
  {
    classNumber: 4,
    medium: 'marathi',
    subjectEnglish: 'Environmental Studies',
    subjectMarathi: 'परिसर अभ्यास',
    titleEnglish: 'Parisar Abhyas Part 2 Standard 4',
    titleMarathi: 'परिसर अभ्यास भाग २ (इतिहास) इयत्ता ४',
    descriptionEnglish: 'Maharashtra State Board Parisar Abhyas Part 2 (Chhatrapati Shivaji Maharaj) for Class 4',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ परिसर अभ्यास भाग २ (छत्रपती शिवाजी महाराज) पाठ्यपुस्तक इयत्ता ४',
    fileName: 'परिसर अभ्यास भाग-2.pdf',
    relativePath: '4rth Std/Marathi medium/परिसर अभ्यास भाग-2.pdf',
  },
  {
    classNumber: 4,
    medium: 'marathi',
    subjectEnglish: 'Environmental Studies',
    subjectMarathi: 'परिसर अभ्यास',
    titleEnglish: 'Parisar Abhyas Part 1 Standard 4',
    titleMarathi: 'परिसर अभ्यास भाग १ इयत्ता ४',
    descriptionEnglish: 'Maharashtra State Board Parisar Abhyas Part 1 for Class 4',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ परिसर अभ्यास भाग १ पाठ्यपुस्तक इयत्ता ४',
    fileName: 'परिसर अभ्यास भाग-१.pdf',
    relativePath: '4rth Std/Marathi medium/परिसर अभ्यास भाग-१.pdf',
  },
  {
    classNumber: 4,
    medium: 'marathi',
    subjectEnglish: 'Marathi',
    subjectMarathi: 'मराठी',
    titleEnglish: 'Balbharati Marathi Standard 4',
    titleMarathi: 'बालभारती मराठी इयत्ता ४',
    descriptionEnglish: 'Maharashtra State Board Balbharati Marathi textbook for Class 4',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ बालभारती मराठी पाठ्यपुस्तक इयत्ता ४',
    fileName: 'बालभारती.pdf',
    relativePath: '4rth Std/Marathi medium/बालभारती.pdf',
  },
  {
    classNumber: 4,
    medium: 'marathi',
    subjectEnglish: 'Hindi',
    subjectMarathi: 'हिंदी',
    titleEnglish: 'Sulabhbharati Hindi Standard 4',
    titleMarathi: 'सुलभभारती हिंदी इयत्ता ४',
    descriptionEnglish: 'Maharashtra State Board Sulabhbharati Hindi for Class 4',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ सुलभभारती हिंदी पाठ्यपुस्तक इयत्ता ४',
    fileName: 'सुलभभारती.pdf',
    relativePath: '4rth Std/Marathi medium/सुलभभारती.pdf',
  },

  // ============================================================
  // CLASS 5
  // ============================================================
  // Marathi Medium
  {
    classNumber: 5,
    medium: 'marathi',
    subjectEnglish: 'English',
    subjectMarathi: 'इंग्रजी',
    titleEnglish: 'English Reader Standard 5',
    titleMarathi: 'इंग्रजी वाचन पुस्तक इयत्ता ५',
    descriptionEnglish: 'Maharashtra State Board English Reader for Class 5',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ इंग्रजी वाचन पुस्तक इयत्ता ५',
    fileName: 'english.pdf',
    relativePath: '5th Std/Marathi medium/english.pdf',
  },
  {
    classNumber: 5,
    medium: 'marathi',
    subjectEnglish: 'Environmental Studies',
    subjectMarathi: 'परिसर अभ्यास',
    titleEnglish: 'Parisar Abhyas Part 2 Standard 5',
    titleMarathi: 'परिसर अभ्यास भाग २ इयत्ता ५',
    descriptionEnglish: 'Maharashtra State Board Parisar Abhyas Part 2 for Class 5',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ परिसर अभ्यास भाग २ पाठ्यपुस्तक इयत्ता ५',
    fileName: 'परिसर अभ्यास भाग-2.pdf',
    relativePath: '5th Std/Marathi medium/परिसर अभ्यास भाग-2.pdf',
  },
  {
    classNumber: 5,
    medium: 'marathi',
    subjectEnglish: 'Environmental Studies',
    subjectMarathi: 'परिसर अभ्यास',
    titleEnglish: 'Parisar Abhyas Part 1 Standard 5',
    titleMarathi: 'परिसर अभ्यास भाग १ इयत्ता ५',
    descriptionEnglish: 'Maharashtra State Board Parisar Abhyas Part 1 for Class 5',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ परिसर अभ्यास भाग १ पाठ्यपुस्तक इयत्ता ५',
    fileName: 'परिसर अभ्यास भाग-१.pdf',
    relativePath: '5th Std/Marathi medium/परिसर अभ्यास भाग-१.pdf',
  },
  {
    classNumber: 5,
    medium: 'marathi',
    subjectEnglish: 'Marathi',
    subjectMarathi: 'मराठी',
    titleEnglish: 'Balbharati Marathi Standard 5',
    titleMarathi: 'बालभारती मराठी इयत्ता ५',
    descriptionEnglish: 'Maharashtra State Board Balbharati Marathi textbook for Class 5',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ बालभारती मराठी पाठ्यपुस्तक इयत्ता ५',
    fileName: 'बालभारती.pdf',
    relativePath: '5th Std/Marathi medium/बालभारती.pdf',
  },
  {
    classNumber: 5,
    medium: 'marathi',
    subjectEnglish: 'English',
    subjectMarathi: 'इंग्रजी',
    titleEnglish: 'My English Book Standard 5',
    titleMarathi: 'माय इंग्लिश बुक इयत्ता ५',
    descriptionEnglish: 'Maharashtra State Board My English Book for Class 5',
    descriptionMarathi: 'महाराष्ट्र राज्य मंडळ माय इंग्लिश बुक पाठ्यपुस्तक इयत्ता ५',
    fileName: 'माय इंग्लिश बुक.pdf',
    relativePath: '5th Std/Marathi medium/माय इंग्लिश बुक.pdf',
  },
];
